### PR TITLE
Remove vivid, add wily and xenial for Kinetic

### PR DESCRIPTION
**Pull request by jacquelinekay**
I'm removing vivid because it's EOL'd. Let me know if it should not be removed, I wasn't quite sure what the right thing was.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Since we are currently still building packages for vivid we should keep mirroring them. Once we stopped the build farm for it we could disable the mirror a couple of weeks later (to ensure that the latest state has propagated). But we could also keep them to have the mirrors have the same state as the official repos.

**Comment by jacquelinekay** [comment]
alright, I restored vivid.

**Comment by tfoote** [comment]
We should add ubuntu armhf I guess we missed that on the mirrors

And we should also add jessie amd64 and arm64.

**Comment by jacquelinekay** [comment]
@tfoote should I add armhf for all versions listed in the file or is there a cutoff (e.g. trusty onwards)? How do I know which version has armhf support?

**Comment by jacquelinekay** [comment]
maybe this is helpful: http://packages.ros.org/ros/ubuntu/lists/

**Comment by tfoote** [comment]
Short answer. We've been building armhf for LTS releases only. For Indigo and Jade, Trusty only. Kinetic we are building Xenial and Jessie which are both stable releases.

The authoritative source for this is the ros_buildfarm_config repo production branch: 
https://github.com/ros-infrastructure/ros_buildfarm_config/blob/production

It is what the buildfarm uses: for example the arm builds are in: 
- https://github.com/ros-infrastructure/ros_buildfarm_config/blob/production/indigo/release-armhf-build.yaml
- https://github.com/ros-infrastructure/ros_buildfarm_config/blob/production/jade/release-armhf-build.yaml
- https://github.com/ros-infrastructure/ros_buildfarm_config/blob/production/kinetic/release-arm-build.yaml

It's also reflected in the status pages for each buildfarm config release build file there's a status page.

**Comment by tfoote** [comment]
Doubled with you on the commit. I added a fix up commit and kept armhf there as we do have some dependencies there that we've provided for convenience: http://packages.ros.org/ros/ubuntu/dists/precise/main/binary-armhf/Packages

**Comment by tfoote** [comment]
I think this is good to merge, but I'd like to hold off until I"m near a test mirror to verify the rollout.

**Comment by Tones29** [comment]
tfoote, did you run a test mirror and can we merge this pull request? The first users are missing the Kinetic packages on the Freiburg mirror.

**Comment by tfoote** [comment]
@Tones29 thanks for the ping. I've tested it and it's running on my test mirror. I had to disable the arm64 lines since apt-mirror does not seem to support them.

https://github.com/ros-infrastructure/mirror/commit/3fbb8315bdb4cf683360cfba197e41c5617fd692

**Pull request merged**
